# render.yaml
services:
  - type: web
    name: game-store-backend
    runtime: docker
    repo: https://github.com/dzikriii24/backend-gamestore  # Ganti dengan repo kamu
    branch: main
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
    healthCheckPath: /api/health-check
    autoDeploy: true

databases:
  - name: gamestoredb
    plan: free
    databaseName: gamestore
    user: gamestore_user